# Generated by Django 5.0.2 on 2024-02-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("gender", models.IntegerField()),
                ("style1", models.IntegerField()),
                ("style2", models.IntegerField()),
                ("style3", models.IntegerField()),
                ("style4", models.IntegerField()),
                ("style5", models.IntegerField()),
                ("style6", models.IntegerField()),
                ("style7", models.IntegerField()),
                ("style8", models.IntegerField()),
                ("MBTI", models.CharField(max_length=200)),
            ],
        ),
    ]
